// This file is automatically generated. Do not edit it directly.
// NOTE: Modified to use environment variables for security
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// ✅ SECURE: Get credentials from environment variables, not hardcoded
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || "https://pgypyipdmrhrutegapsx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY;

if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  console.error(
    'Missing Supabase configuration. Please set VITE_SUPABASE_URL and VITE_SUPABASE_ANON_KEY in your .env file.'
  );
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});