// This file is automatically generated. Do not edit it directly.
// NOTE: Modified to use environment variables for security
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Supabase configuration - reads from environment variables
// For local dev: .env.local overrides .env
// SECURITY: No hardcoded fallbacks - environment variables are required
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Fail fast if environment variables are not configured
if (!SUPABASE_URL) {
  throw new Error('VITE_SUPABASE_URL environment variable is required. Check your .env file.');
}
if (!SUPABASE_PUBLISHABLE_KEY) {
  throw new Error('VITE_SUPABASE_PUBLISHABLE_KEY environment variable is required. Check your .env file.');
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});